name: Feature request
description: Sugerir uma nova funcionalidade
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema a ser resolvido
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solução sugerida
``
